### ISSUE TITLE
Meta Issue: Meta Issue: IA Improvements from User Feedback 

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#3971]
## IA Improvements from User Feedback (Goodies)

DuckDuckGo has [over 1000 IAs](https://duck.co/ia) in production. Utilizing user feedback, we want to make these IAs even more awesome! Below is a list of tasks that need to be completed for existing IAs. 

#### High Priority
  - [ ] [Time Zone: Support "Time in <time_zone>" queries](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4004)
  - [ ] [Reference: New ASCII Codes Table](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3991)
  - [x] ~~[Reference: New HTML Entities Table](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3998)~~
  - [x] ~~[Solar System: show in different unit of measure?](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3870)~~

#### Low Hanging Fruit
  - [ ] [Migrate Triggers from Package Tracking Goodie to Spice](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3973)
  - [x] ~~[Base: Overtriggering](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3985)~~
  - [x] ~~[Conversions: Mistaking MB for Mb](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3990)~~
  - [x] ~~[Conversions: Round to appropriate decimal place](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3984)~~

#### Discussion
  - [ ] [Conversions: Trigger mph to kmh conversion](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3877)

**Comment by pjhampton** [comment]
Hey @duckduckgo/duckduckhack-contributors! 

Is anybody interested by any of the above issues? 🚀  😄

**Comment by pjhampton** [comment]
Closing for now. If anybody is following this issue, please check out https://duckduckhack.com/issues instead 👍
